// <auto-generated />
namespace Taşınmaz_Projesi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tasinmaz : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tasinmaz));
        
        string IMigrationMetadata.Id
        {
            get { return "202011030612094_tasinmaz"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
